[package]
name = "body-graphs"
version = "0.1.0"
authors = ["Chris Lieb <chris.lieb@gmail.com>"]
edition = "2024"

[dependencies]
calamine = "~0.32"
clap = "~4.5"
env_logger = "~0.11.8"
log = "~0.4"
tempfile = "~3.24"
time = { version="~0.3", features=["macros", "formatting"] }
